<?php

namespace Database\Seeders;

use App\Models\CourtSchedule;
use App\Models\Lawyer;
use App\Models\LegalCase;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // --- Lawyers ---
        $lawyers = [
            ['name' => 'Adv. Ramesh Prasad Sharma', 'email' => 'ramesh.sharma@nyayamitra.np', 'phone' => '9841012345', 'specialization' => 'Criminal Law', 'bar_number' => 'NBA-2010-1234', 'experience_years' => 16, 'bio' => 'Adv. Ramesh Prasad Sharma is a seasoned criminal law practitioner with over 16 years of experience in the Supreme Court and High Courts of Nepal. He has successfully defended over 200 criminal cases including high-profile murder trials and fraud cases. Known for his meticulous preparation and persuasive courtroom arguments.', 'is_available' => true],
            ['name' => 'Adv. Sita Devi Adhikari', 'email' => 'sita.adhikari@nyayamitra.np', 'phone' => '9851023456', 'specialization' => 'Family Law', 'bar_number' => 'NBA-2012-2345', 'experience_years' => 14, 'bio' => 'Adv. Sita Devi Adhikari specializes in family law matters including divorce, child custody, property disputes, and domestic violence cases. She is a strong advocate for women\'s rights and has been honored by the Nepal Bar Association for her pro-bono contributions.', 'is_available' => true],
            ['name' => 'Adv. Bikram Thapa', 'email' => 'bikram.thapa@nyayamitra.np', 'phone' => '9861034567', 'specialization' => 'Civil Law', 'bar_number' => 'NBA-2008-3456', 'experience_years' => 18, 'bio' => 'Adv. Bikram Thapa is one of Nepal\'s leading civil litigation lawyers with expertise in land disputes, contract law, and property rights. He has handled landmark cases that set important precedents in Nepali civil law.', 'is_available' => true],
            ['name' => 'Adv. Priya Maharjan', 'email' => 'priya.maharjan@nyayamitra.np', 'phone' => '9801045678', 'specialization' => 'Constitutional Law', 'bar_number' => 'NBA-2015-4567', 'experience_years' => 11, 'bio' => 'Adv. Priya Maharjan is a rising star in constitutional law, having argued multiple public interest litigations before the Supreme Court of Nepal. She is passionate about human rights and fundamental freedoms.', 'is_available' => true],
            ['name' => 'Adv. Suresh Bahadur Rai', 'email' => 'suresh.rai@nyayamitra.np', 'phone' => '9811056789', 'specialization' => 'Commercial Law', 'bar_number' => 'NBA-2009-5678', 'experience_years' => 17, 'bio' => 'Adv. Suresh Bahadur Rai specializes in commercial and corporate law including company formation, mergers, banking disputes, and intellectual property. He advises several major Nepali corporations and international businesses operating in Nepal.', 'is_available' => true],
            ['name' => 'Adv. Anita Gurung', 'email' => 'anita.gurung@nyayamitra.np', 'phone' => '9821067890', 'specialization' => 'Criminal Law', 'bar_number' => 'NBA-2014-6789', 'experience_years' => 12, 'bio' => 'Adv. Anita Gurung is a dedicated criminal defense lawyer known for her empathetic approach and tireless advocacy. She has a special focus on juvenile justice and rehabilitation-centered sentencing.', 'is_available' => false],
            ['name' => 'Adv. Deepak Khadka', 'email' => 'deepak.khadka@nyayamitra.np', 'phone' => '9841078901', 'specialization' => 'Civil Law', 'bar_number' => 'NBA-2011-7890', 'experience_years' => 15, 'bio' => 'Adv. Deepak Khadka handles complex civil disputes involving property, inheritance, and contractual obligations. He is known for his analytical approach and skill in mediation and alternative dispute resolution.', 'is_available' => true],
            ['name' => 'Adv. Kavita Poudel', 'email' => 'kavita.poudel@nyayamitra.np', 'phone' => '9851089012', 'specialization' => 'Family Law', 'bar_number' => 'NBA-2016-8901', 'experience_years' => 10, 'bio' => 'Adv. Kavita Poudel focuses on family law with a compassionate approach to sensitive matters. She handles divorce proceedings, alimony cases, child protection, and adoption cases with professionalism and care.', 'is_available' => true],
            ['name' => 'Adv. Rajan Shrestha', 'email' => 'rajan.shrestha@nyayamitra.np', 'phone' => '9861090123', 'specialization' => 'Commercial Law', 'bar_number' => 'NBA-2007-9012', 'experience_years' => 19, 'bio' => 'Adv. Rajan Shrestha is a veteran commercial lawyer with nearly two decades of experience. He has expertise in international trade law, arbitration, and has represented Nepal in several bilateral trade dispute resolutions.', 'is_available' => true],
            ['name' => 'Adv. Mina Tamang', 'email' => 'mina.tamang@nyayamitra.np', 'phone' => '9801001234', 'specialization' => 'Constitutional Law', 'bar_number' => 'NBA-2013-0123', 'experience_years' => 13, 'bio' => 'Adv. Mina Tamang is a constitutional lawyer dedicated to indigenous rights and environmental law. She has filed numerous PILs for the protection of indigenous communities and natural resources in Nepal.', 'is_available' => true],
        ];

        foreach ($lawyers as $lawyer) {
            Lawyer::create($lawyer);
        }

        // --- Legal Cases ---
        $cases = [
            ['case_number' => 'CR-2026-001', 'title' => 'State vs. Hari Bahadur Tamang', 'plaintiff' => 'Government of Nepal', 'defendant' => 'Hari Bahadur Tamang', 'court' => 'Kathmandu District Court', 'judge' => 'Hon. Justice Narayan Prasad', 'case_type' => 'Criminal', 'status' => 'In Progress', 'filed_date' => '2026-01-15', 'next_hearing' => '2026-03-25 10:00:00', 'verdict' => null, 'description' => 'Criminal case involving alleged fraud and embezzlement of company funds amounting to NPR 50 lakhs. The defendant is accused of misappropriating funds from Himalayan Trading Co. over a period of 3 years.'],
            ['case_number' => 'CV-2025-042', 'title' => 'Shrestha Family Land Dispute', 'plaintiff' => 'Ram Kumar Shrestha', 'defendant' => 'Bishnu Shrestha', 'court' => 'Lalitpur District Court', 'judge' => 'Hon. Justice Kamala Devi', 'case_type' => 'Civil', 'status' => 'In Progress', 'filed_date' => '2025-08-20', 'next_hearing' => '2026-03-28 11:00:00', 'verdict' => null, 'description' => 'Property dispute over ancestral land measuring 10 ropani in Lalitpur. The plaintiff claims sole ownership based on a will, while the defendant contests citing equal inheritance rights under the new civil code.'],
            ['case_number' => 'FM-2026-015', 'title' => 'Pokharel vs. Pokharel Divorce', 'plaintiff' => 'Sunita Pokharel', 'defendant' => 'Manoj Pokharel', 'court' => 'Bhaktapur District Court', 'judge' => 'Hon. Justice Binod Sharma', 'case_type' => 'Family', 'status' => 'Pending', 'filed_date' => '2026-02-10', 'next_hearing' => '2026-04-02 14:00:00', 'verdict' => null, 'description' => 'Divorce petition filed by Sunita Pokharel citing irreconcilable differences and seeking custody of two minor children. The case also involves division of marital property.'],
            ['case_number' => 'CM-2025-088', 'title' => 'Everest Corp vs. Nepal Bank Ltd', 'plaintiff' => 'Everest Corporation Pvt. Ltd.', 'defendant' => 'Nepal Bank Limited', 'court' => 'Commercial Court, Kathmandu', 'judge' => 'Hon. Justice Prakash Rana', 'case_type' => 'Commercial', 'status' => 'Adjourned', 'filed_date' => '2025-06-15', 'next_hearing' => '2026-04-10 10:30:00', 'verdict' => null, 'description' => 'Commercial dispute regarding loan restructuring and alleged breach of banking agreement. The plaintiff claims the bank unilaterally changed loan terms causing significant financial loss.'],
            ['case_number' => 'CN-2025-003', 'title' => 'PIL: Right to Clean Environment', 'plaintiff' => 'Environmental Protection Forum Nepal', 'defendant' => 'Ministry of Environment', 'court' => 'Supreme Court of Nepal', 'judge' => 'Hon. Chief Justice Deepak Raj', 'case_type' => 'Constitutional', 'status' => 'In Progress', 'filed_date' => '2025-03-22', 'next_hearing' => '2026-03-30 11:00:00', 'verdict' => null, 'description' => 'Public Interest Litigation challenging the government\'s environmental impact assessment policies. The petitioner argues current policies are insufficient to protect citizens\' constitutional right to a clean environment.'],
            ['case_number' => 'CR-2025-156', 'title' => 'State vs. Dipak Chaudhary', 'plaintiff' => 'Government of Nepal', 'defendant' => 'Dipak Chaudhary', 'court' => 'Morang District Court', 'judge' => 'Hon. Justice Sarita Kumari', 'case_type' => 'Criminal', 'status' => 'Disposed', 'filed_date' => '2025-01-10', 'next_hearing' => null, 'verdict' => 'The court finds the defendant guilty of theft under Section 205 of the Muluki Criminal Code. Sentenced to 2 years imprisonment with a fine of NPR 50,000. The sentence may be appealed within 35 days.', 'description' => 'Criminal case involving theft of electronic goods from a warehouse in Biratnagar industrial zone valued at approximately NPR 15 lakhs.'],
            ['case_number' => 'CV-2026-023', 'title' => 'Maharjan vs. Metropolitan City', 'plaintiff' => 'Rajendra Maharjan', 'defendant' => 'Kathmandu Metropolitan City', 'court' => 'High Court Patan', 'judge' => 'Hon. Justice Hari Prasad', 'case_type' => 'Civil', 'status' => 'Pending', 'filed_date' => '2026-02-28', 'next_hearing' => '2026-04-05 10:00:00', 'verdict' => null, 'description' => 'Civil case challenging the compulsory acquisition of private land for a road widening project. The plaintiff demands fair market compensation as guaranteed by the Constitution.'],
            ['case_number' => 'FM-2025-078', 'title' => 'Basnet Child Custody Case', 'plaintiff' => 'Gita Basnet', 'defendant' => 'Prakash Basnet', 'court' => 'Kaski District Court', 'judge' => 'Hon. Justice Laxmi Dhakal', 'case_type' => 'Family', 'status' => 'Disposed', 'filed_date' => '2025-04-12', 'next_hearing' => null, 'verdict' => 'Custody of both minor children granted to the mother, Gita Basnet, with visitation rights for the father on weekends and holidays. Father ordered to pay NPR 25,000 monthly child support.', 'description' => 'Child custody dispute following divorce. Both parents sought primary custody of two children aged 5 and 8 years.'],
            ['case_number' => 'CM-2026-011', 'title' => 'Yeti Airlines vs. Insurance Co.', 'plaintiff' => 'Yeti Airlines Pvt. Ltd.', 'defendant' => 'Nepal Insurance Company', 'court' => 'Commercial Court, Kathmandu', 'judge' => 'Hon. Justice Prakash Rana', 'case_type' => 'Commercial', 'status' => 'In Progress', 'filed_date' => '2026-01-20', 'next_hearing' => '2026-04-08 14:00:00', 'verdict' => null, 'description' => 'Insurance claim dispute over aircraft damage. The airline claims NPR 5 crore in damages while the insurance company disputes the claim citing policy exclusions.'],
            ['case_number' => 'CN-2026-007', 'title' => 'PIL: Digital Privacy Rights', 'plaintiff' => 'Digital Rights Nepal', 'defendant' => 'Government of Nepal', 'court' => 'Supreme Court of Nepal', 'judge' => 'Hon. Chief Justice Deepak Raj', 'case_type' => 'Constitutional', 'status' => 'Pending', 'filed_date' => '2026-03-01', 'next_hearing' => '2026-04-15 11:00:00', 'verdict' => null, 'description' => 'PIL challenging certain provisions of the proposed Cyber Security Bill, arguing they violate citizens\' right to privacy and freedom of expression guaranteed by the Constitution.'],
            ['case_number' => 'CR-2026-034', 'title' => 'State vs. Kiran Magar', 'plaintiff' => 'Government of Nepal', 'defendant' => 'Kiran Magar', 'court' => 'Chitwan District Court', 'judge' => 'Hon. Justice Mohan Acharya', 'case_type' => 'Criminal', 'status' => 'Appealed', 'filed_date' => '2025-11-05', 'next_hearing' => '2026-04-20 10:00:00', 'verdict' => 'Original verdict: Acquitted by Chitwan District Court. The prosecution has filed an appeal in the High Court.', 'description' => 'Drug trafficking case involving allegedly smuggling controlled substances across the Nepal-India border. The defendant was acquitted by the district court due to insufficient evidence.'],
            ['case_number' => 'CV-2025-111', 'title' => 'Kathmandu Heritage Trust vs. Developers', 'plaintiff' => 'Kathmandu Heritage Trust', 'defendant' => 'Modern Builders Pvt. Ltd.', 'court' => 'High Court Patan', 'judge' => 'Hon. Justice Hari Prasad', 'case_type' => 'Civil', 'status' => 'In Progress', 'filed_date' => '2025-09-05', 'next_hearing' => '2026-03-22 10:00:00', 'verdict' => null, 'description' => 'Case challenging illegal construction adjacent to a UNESCO World Heritage Site in Kathmandu Durbar Square. The plaintiff seeks demolition of the unauthorized structure and restoration of the heritage zone.'],
            ['case_number' => 'CM-2025-065', 'title' => 'Tech Solutions vs. Digital Nepal Inc.', 'plaintiff' => 'Tech Solutions Nepal', 'defendant' => 'Digital Nepal Inc.', 'court' => 'Commercial Court, Kathmandu', 'judge' => 'Hon. Justice Prakash Rana', 'case_type' => 'Commercial', 'status' => 'Disposed', 'filed_date' => '2025-05-18', 'next_hearing' => null, 'verdict' => 'The court ruled in favor of the plaintiff. Digital Nepal Inc. ordered to pay NPR 1.2 crore in damages for breach of software licensing agreement and unauthorized use of proprietary code.', 'description' => 'Intellectual property dispute over unauthorized copying and distribution of proprietary software. The plaintiff alleges the defendant reverse-engineered their enterprise management system.'],
            ['case_number' => 'FM-2026-029', 'title' => 'Karki Inheritance Dispute', 'plaintiff' => 'Suman Karki', 'defendant' => 'Rajan Karki & Others', 'court' => 'Rupandehi District Court', 'judge' => 'Hon. Justice Bimala Pant', 'case_type' => 'Family', 'status' => 'In Progress', 'filed_date' => '2026-02-05', 'next_hearing' => '2026-04-12 11:00:00', 'verdict' => null, 'description' => 'Inheritance dispute involving division of ancestral property worth approximately NPR 3 crore among siblings. The dispute centers around the validity of a purported will.'],
            ['case_number' => 'CR-2025-200', 'title' => 'State vs. Organized Crime Ring', 'plaintiff' => 'Government of Nepal', 'defendant' => 'Rajesh Kumar & 5 Others', 'court' => 'Kathmandu District Court', 'judge' => 'Hon. Justice Narayan Prasad', 'case_type' => 'Criminal', 'status' => 'In Progress', 'filed_date' => '2025-10-15', 'next_hearing' => '2026-03-26 10:00:00', 'verdict' => null, 'description' => 'Major organized crime case involving money laundering, extortion, and racketeering. Six defendants arrested as part of a joint operation by Nepal Police and the Central Investigation Bureau.'],
        ];

        foreach ($cases as $case) {
            LegalCase::create($case);
        }

        // --- Court Schedules ---
        $schedules = [
            ['legal_case_id' => 1, 'court_room' => 'Room 201', 'hearing_date' => '2026-01-20', 'hearing_time' => '10:00', 'judge' => 'Hon. Justice Narayan Prasad', 'status' => 'Completed', 'notes' => 'Initial hearing completed. Charges read and defendant pleaded not guilty.'],
            ['legal_case_id' => 1, 'court_room' => 'Room 201', 'hearing_date' => '2026-02-15', 'hearing_time' => '10:00', 'judge' => 'Hon. Justice Narayan Prasad', 'status' => 'Completed', 'notes' => 'Prosecution presented documentary evidence. Three witnesses examined.'],
            ['legal_case_id' => 1, 'court_room' => 'Room 201', 'hearing_date' => '2026-03-25', 'hearing_time' => '10:00', 'judge' => 'Hon. Justice Narayan Prasad', 'status' => 'Scheduled', 'notes' => 'Defense to present its witnesses. Cross-examination expected.'],
            ['legal_case_id' => 2, 'court_room' => 'Room 105', 'hearing_date' => '2025-09-10', 'hearing_time' => '11:00', 'judge' => 'Hon. Justice Kamala Devi', 'status' => 'Completed', 'notes' => 'Both parties presented initial land documents. Survey ordered.'],
            ['legal_case_id' => 2, 'court_room' => 'Room 105', 'hearing_date' => '2025-11-20', 'hearing_time' => '11:00', 'judge' => 'Hon. Justice Kamala Devi', 'status' => 'Completed', 'notes' => 'Land survey report submitted. Both parties contested the findings.'],
            ['legal_case_id' => 2, 'court_room' => 'Room 105', 'hearing_date' => '2026-03-28', 'hearing_time' => '11:00', 'judge' => 'Hon. Justice Kamala Devi', 'status' => 'Scheduled', 'notes' => 'Final arguments from both sides expected.'],
            ['legal_case_id' => 3, 'court_room' => 'Room 302', 'hearing_date' => '2026-04-02', 'hearing_time' => '14:00', 'judge' => 'Hon. Justice Binod Sharma', 'status' => 'Scheduled', 'notes' => 'First hearing. Mediation to be attempted before formal proceedings.'],
            ['legal_case_id' => 4, 'court_room' => 'Room 401', 'hearing_date' => '2025-07-10', 'hearing_time' => '10:30', 'judge' => 'Hon. Justice Prakash Rana', 'status' => 'Completed', 'notes' => 'Initial arguments heard. Bank submitted original loan documents.'],
            ['legal_case_id' => 4, 'court_room' => 'Room 401', 'hearing_date' => '2025-10-20', 'hearing_time' => '10:30', 'judge' => 'Hon. Justice Prakash Rana', 'status' => 'Postponed', 'notes' => 'Adjourned due to defendant counsel\'s absence. Rescheduled.'],
            ['legal_case_id' => 4, 'court_room' => 'Room 401', 'hearing_date' => '2026-04-10', 'hearing_time' => '10:30', 'judge' => 'Hon. Justice Prakash Rana', 'status' => 'Scheduled', 'notes' => 'Expert financial witness to testify on loan restructuring terms.'],
            ['legal_case_id' => 5, 'court_room' => 'Courtroom 1', 'hearing_date' => '2025-05-15', 'hearing_time' => '11:00', 'judge' => 'Hon. Chief Justice Deepak Raj', 'status' => 'Completed', 'notes' => 'Preliminary hearing. Government asked for 60 days to file counter-affidavit.'],
            ['legal_case_id' => 5, 'court_room' => 'Courtroom 1', 'hearing_date' => '2025-09-10', 'hearing_time' => '11:00', 'judge' => 'Hon. Chief Justice Deepak Raj', 'status' => 'Completed', 'notes' => 'Both parties argued on merits. Expert environmental committee report discussed.'],
            ['legal_case_id' => 5, 'court_room' => 'Courtroom 1', 'hearing_date' => '2026-03-30', 'hearing_time' => '11:00', 'judge' => 'Hon. Chief Justice Deepak Raj', 'status' => 'Scheduled', 'notes' => 'Final hearing. Verdict expected within 30 days.'],
            ['legal_case_id' => 7, 'court_room' => 'Room 203', 'hearing_date' => '2026-04-05', 'hearing_time' => '10:00', 'judge' => 'Hon. Justice Hari Prasad', 'status' => 'Scheduled', 'notes' => 'First hearing on land compensation petition.'],
            ['legal_case_id' => 9, 'court_room' => 'Room 401', 'hearing_date' => '2026-02-20', 'hearing_time' => '14:00', 'judge' => 'Hon. Justice Prakash Rana', 'status' => 'Completed', 'notes' => 'Policy documents and damage assessment reports submitted.'],
            ['legal_case_id' => 9, 'court_room' => 'Room 401', 'hearing_date' => '2026-04-08', 'hearing_time' => '14:00', 'judge' => 'Hon. Justice Prakash Rana', 'status' => 'Scheduled', 'notes' => 'Insurance expert witness to present findings on policy coverage.'],
            ['legal_case_id' => 10, 'court_room' => 'Courtroom 2', 'hearing_date' => '2026-04-15', 'hearing_time' => '11:00', 'judge' => 'Hon. Chief Justice Deepak Raj', 'status' => 'Scheduled', 'notes' => 'Preliminary hearing. Show cause notice to be issued to the government.'],
            ['legal_case_id' => 11, 'court_room' => 'Room 102', 'hearing_date' => '2026-04-20', 'hearing_time' => '10:00', 'judge' => 'Hon. Justice Mohan Acharya', 'status' => 'Scheduled', 'notes' => 'Appeal hearing. Prosecution to present additional evidence.'],
            ['legal_case_id' => 12, 'court_room' => 'Room 203', 'hearing_date' => '2025-10-10', 'hearing_time' => '10:00', 'judge' => 'Hon. Justice Hari Prasad', 'status' => 'Completed', 'notes' => 'UNESCO heritage guidelines discussed. Site inspection ordered.'],
            ['legal_case_id' => 12, 'court_room' => 'Room 203', 'hearing_date' => '2026-03-22', 'hearing_time' => '10:00', 'judge' => 'Hon. Justice Hari Prasad', 'status' => 'Scheduled', 'notes' => 'Site inspection report to be presented. Expert archaeological testimony expected.'],
            ['legal_case_id' => 14, 'court_room' => 'Room 301', 'hearing_date' => '2026-04-12', 'hearing_time' => '11:00', 'judge' => 'Hon. Justice Bimala Pant', 'status' => 'Scheduled', 'notes' => 'Will authenticity to be examined. Handwriting expert report awaited.'],
            ['legal_case_id' => 15, 'court_room' => 'Room 201', 'hearing_date' => '2025-11-15', 'hearing_time' => '10:00', 'judge' => 'Hon. Justice Narayan Prasad', 'status' => 'Completed', 'notes' => 'Charges read against all six defendants. Bail denied for primary accused.'],
            ['legal_case_id' => 15, 'court_room' => 'Room 201', 'hearing_date' => '2026-01-25', 'hearing_time' => '10:00', 'judge' => 'Hon. Justice Narayan Prasad', 'status' => 'Completed', 'notes' => 'CIB presented financial transaction records and surveillance evidence.'],
            ['legal_case_id' => 15, 'court_room' => 'Room 201', 'hearing_date' => '2026-03-26', 'hearing_time' => '10:00', 'judge' => 'Hon. Justice Narayan Prasad', 'status' => 'Scheduled', 'notes' => 'Defense to begin cross-examination of prosecution witnesses.'],
        ];

        foreach ($schedules as $schedule) {
            CourtSchedule::create($schedule);
        }
    }
}
